### ISSUE TITLE
有计划对齐到1.9.3.1吗？

### ISSUE THREAD

**Issue by pinghe** [LomoX-Offical/nginx-openresty-windows#10]
有计划对齐到1.9.3.1吗？

**Comment by zqzjz0911** [comment]
有计划的，最近就会更新了。谢谢提醒，请继续关注。

**Comment by pinghe** [comment]
openresty 不知道会不会升级nginx core 到1.9.4 , 1.9.4 包含 Feature: multiple "sub_filter" directives can be used simultaneously. 非常有用

**Comment by zqzjz0911** [comment]
nginx core 我们现在不跟 openresty 走。我们使用 官方 stable 版本 1.8.0，开发版本有一定的使用风险

**Comment by pinghe** [comment]
能否同时提供一个Mainline version，对齐nginx Mainline version。有些特性在主分支才有。

**Comment by caidongyun** [comment]
分支的方式可以考虑？.

柱子时间够么？     是否有人可以接手维护这些分支?

**Comment by zqzjz0911** [comment]
这样还是分开搞吧，开一个 develop 分支，一个 stable 分支

**Comment by pinghe** [comment]
多谢！ 很高兴这么快就看到了 1.9.4.1001 版本发布。感谢

**Comment by zqzjz0911** [comment]
这个是开发版本呢。
