### ISSUE TITLE
win64  1.9.7.1002 运行报错

### ISSUE THREAD

**Issue by houhlin** [LomoX-Offical/nginx-openresty-windows#14]
您好，使用win64版openresty出错，麻烦 请帮看下，多谢！
 执行lua 脚本出错，提示无法创建文件  报错信息如下  :  
    [error] 2656#2796: *5345 CreateFile() "C:\ngx_openresty-1.9.7/html/test_lua" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /test_lua HTTP/1.1", host: "localhost"

系统：win10  64位

**Comment by BloodyKnight** [comment]
您好，能把配置文件贴一下吗？

**Comment by houhlin** [comment]
感谢您的回复，已找到原因，是
 location ~ .*.(js|css)?$ { 
		expires 1h; 
 }  引起的。 
  还有一个问题，就是在win7 64位里运行正常，但在win10 64位  执行 -t  或者 -s reload 、-s stop 只会出现一个一闪而过的弹框没任何效果。

**Comment by zqzjz0911** [comment]
为了搜索方便，麻烦 houhlin 新开一个 issue ？

**Comment by houhlin** [comment]
好的，那个配置 感觉也很正常，但是会报上面的错误  是什么原因呢

**Comment by zqzjz0911** [comment]
跟这个没关系，麻烦贴一下全部的配置？

**Comment by houhlin** [comment]
nginx.conf 文件：
#user  nobody;
worker_processes  2; #cpu cores

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;

worker_rlimit_nofile 6555;

events {
	worker_connections  1024;
}

http {
    include       mime.types;  
    default_type  application/octet-stream; 
	charset utf-8;
		
	sendfile on; 
	tcp_nopush on; 
	tcp_nodelay on; 	
	keepalive_timeout 120; 
	
	#gzip model
	gzip on; 
	
	log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
    access_log  logs/access.log  main;
	
	lua_package_path "$prefix/?.luac;$prefix/?.lua;;";
	include lua.conf;

}

lua.conf  文件：
server {		
	listen 80; 
	charset utf-8;
	server_name localhost; 
	#index index.html index.htm ;
	root html;	
	location / {
		index  index.html index.htm;		
	} 

	location /test_lua {
		default_type 'text/html';
		lua_code_cache off; #close lua_code_cache
		content_by_lua 'ngx.say("Hello World")';
	}
	
	location /test02_lua {
		default_type 'text/html';
		lua_code_cache off;
		content_by_lua_file servers/lua/test01.lua; #lua file
	}
	
	location /lua_jit_version {
		default_type 'text/html';
		content_by_lua_file servers/lua/lua_jit_version.lua;
	}
	
	location ~ .*.(htm|html|gif|jpg|jpeg|png|bmp|swf|ioc|rar|zip|txt|flv|mid|doc|ppt|pdf|xls|mp3|wma)$ { 
		expires 15d; 
	}
	location ~ .*.(js|css)?$ { 
		expires 1h; 
	}	

	# pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
	#
	#location ~ \.php$ {
	#    root           html;
	#    fastcgi_pass   127.0.0.1:9000;
	#    fastcgi_index  index.php;
	#    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
	#    include        fastcgi_params;
	#}

	# deny access to .htaccess files, if Apache's document root
	# concurs with nginx's one
	#
	#location ~ /\.ht {
	#    deny  all;
	#}
}

假如注释掉那一块就访问正常了

**Comment by zqzjz0911** [comment]
这是 location 的优先级问题，请多尝试，比如 把 location /test_lua 改成 location =  /test_lua ，看如何。

**Comment by houhlin** [comment]
感谢，是这个原因引起的
