### ISSUE TITLE
win10 64位 执行 -t 或者 -s reload 、-s stop 之类的命令无效果

### ISSUE THREAD

**Issue by houhlin** [LomoX-Offical/nginx-openresty-windows#15]
您好 
使用win64版openresty   在win7 64位 里运行正常，但在win10 64位 执行 -t 或者 -s reload 、-s stop 只会出现一个一闪而过的弹框实际没任何效果。

**Comment by zqzjz0911** [comment]
我们这边测试的确会弹黑框，但 reload 和 stop 的动作会执行。麻烦贴一下配置。

**Comment by zqzjz0911** [comment]
也贴出你 nginx 的运行 命令行以及 reload 和 stop 的运行 命令行。

**Comment by houhlin** [comment]
感谢你的回复，配置如下：
nginx.conf 文件：
#user nobody;
worker_processes 2; #cpu cores

#error_log logs/error.log;
#error_log logs/error.log notice;
#error_log logs/error.log info;

#pid logs/nginx.pid;

worker_rlimit_nofile 6555;

events {
worker_connections 1024;
}

http {
include mime.types;

default_type application/octet-stream; 
charset utf-8;

sendfile on; 
tcp_nopush on; 
tcp_nodelay on;     
keepalive_timeout 120; 

#gzip model
gzip on; 

log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                  '$status $body_bytes_sent "$http_referer" '
                  '"$http_user_agent" "$http_x_forwarded_for"';
access_log  logs/access.log  main;

lua_package_path "$prefix/?.luac;$prefix/?.lua;;";
include lua.conf;
}

lua.conf 文件：
server {

listen 80; 
charset utf-8;
server_name localhost; 
#index index.html index.htm ;
root html;

location / {
index index.html index.htm;

}

location /test_lua {
    default_type 'text/html';
    lua_code_cache off; #close lua_code_cache
    content_by_lua 'ngx.say("Hello World")';
}

location /test02_lua {
    default_type 'text/html';
    lua_code_cache off;
    content_by_lua_file servers/lua/test01.lua; #lua file
}

location /lua_jit_version {
    default_type 'text/html';
    content_by_lua_file servers/lua/lua_jit_version.lua;
}

location ~ .*.(htm|html|gif|jpg|jpeg|png|bmp|swf|ioc|rar|zip|txt|flv|mid|doc|ppt|pdf|xls|mp3|wma)$ { 
    expires 15d; 
}
location ~ .*.(js|css)?$ { 
    expires 1h; 
}   

# pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
#
#location ~ \.php$ {
#    root           html;
#    fastcgi_pass   127.0.0.1:9000;
#    fastcgi_index  index.php;
#    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
#    include        fastcgi_params;
#}

# deny access to .htaccess files, if Apache's document root
# concurs with nginx's one
#
#location ~ /\.ht {
#    deny  all;
#}
}

运行命令：
nginx -t
nginx -s reload
nginx -s stop

**Comment by houhlin** [comment]
抱歉，格式有些问题 ，还用再贴一次吗

**Comment by zqzjz0911** [comment]
我这边重现了一下，reload stop 都是可以正常执行的，黑框是因为您的 cmd 启动 不是以管理员权限运行，-t 启动会变成后台程序，建议您使用 process explorer 等第三方进程监控软件来监控 nginx 的命令执行情况。看看进程是否有reload 和 stop 的动作执行。

**Comment by houhlin** [comment]
感谢，使用管理员权限运行下，  运行正常了。非管理员权限的话 一些命令还是无法执行

**Comment by zqzjz0911** [comment]
star 一个吧，谢谢哈。
