### ISSUE TITLE
关于C语言dll中的变量共享问题

### ISSUE THREAD

**Issue by foxericlee1** [LomoX-Offical/nginx-openresty-windows#17]
Hi buddy,
我用nginx+lua+c/c++做数据处理的服务器，希望在内存中做缓存。我将nginx的Worker数量调整为1，理论上讲，应该就是单进程，应当可以从dll中传出缓存指针，并在下次的传入dll中使用。但测试后发现，不可使用，nginx直接重启。
请问哪位知道原因，并给我一个可行的方案？
另外，Windows64位版的服务器不可以将userdata存入全局共享内存，写入马上读取为nil

**Comment by zqzjz0911** [comment]
直接使用 openresty 的 ngx_lua 模块的 ngx.shared_dict 就可以做缓存了啊。

**Comment by zqzjz0911** [comment]
userdata 不可以，lua 的 shared_dict 只支持 这几种类型的数据存储，number，boolean，string，所以最好的解决方法就是把 你的 userdata 序列化成一个字符串，然后传入，取出的时候再反序列化出来。

**Comment by foxericlee1** [comment]
Hi zqzjz0911:
首先非常感谢你的热心回复。我将c中的指针转为字符串后传入lua，并保存到shared_dict。但是不同跨越http request，这个指针是无效的。当然，一个http request中是可以了。所以，我估计，即使将worker设置为1个，在每次http request中，都有不同的堆栈和运行环境。同时，我认为以目前情况，openresty很难做到有状态的大数据量计算任务（例如在内存中的拓扑分析，先要建立拓扑结构，然后再计算。拓扑不是每次http request再请求的），我本打算将openresty应用到这种场景中，但我还没有找到这样的方案。加上redis固然是一种办法，但序列化->存储->反序列化的过程耗时太长。不知道有大拿能够有办法没有。
最后说一下，在没有办法的情况下，我选择了FastCGI技术，然后用C++实现了数据缓存和计算的部分。

**Comment by zqzjz0911** [comment]
序列化指针会引起问题的，序列化整个对象才能跨进程，这样有状态的请求也是可以处理。可以考虑一下哈。
