### ISSUE TITLE
'ngx_http_lua_ffi_semaphore_new': 找不到指定的程序

### ISSUE THREAD

**Issue by aa851853** [LomoX-Offical/nginx-openresty-windows#18]
你好，我在使用（Nginx Openresty For Windows 版本号:1.9.10.1001）时发现报如下错误，请问这个版本是不支持semaphore的吗？

错误: nginx/x\semaphore.lua:64: cannot resolve symbol 'ngx_http_lua_ffi_semaphore_new': 找不到指定的程序。

**Comment by BloodyKnight** [comment]
你好，这个问题在最新的发布版本1.9.12.1001中已经修复了。
谢谢你的反馈！
