### ISSUE TITLE
使用-p和-c参数启动时，提示找不到指令 lua_package_path

### ISSUE THREAD

**Issue by JackFong** [LomoX-Offical/nginx-openresty-windows#19]
您好！

我正在Windows 10上使用1.9.101001版的64位程序。如果直接启动则没有问题，但是如果指定-p和-c参数后，则报错“unknown directive "lua_package_path"。
是不是我忽略了那个安装步骤或者启动参数？
望指教。
谢谢

**Comment by BloodyKnight** [comment]
你好，请问启动的具体命令行是什么样子的，方便贴一下吗，还有你使用的版本是我们发布的二进制打包文件，还是自己编译的？

**Comment by JackFong** [comment]
谢谢您的答复。问题解决了。我之前不知道在Windows下当要指定prefix时，必须在prefix的目录里运行nginx命令。所以，当我切换到prefix目录下启动nginx时就正常了。
