### ISSUE TITLE
问题：1.9.10.1001到1.9.12.1001，nginx.pdb体积缩减将近2/3，是因为调整了编译调试参数的原因吗？

### ISSUE THREAD

**Issue by warmchang** [LomoX-Offical/nginx-openresty-windows#20]
问题：1.9.10.1001到1.9.12.1001，nginx.pdb体积缩减将近2/3，是因为调整了编译调试参数的原因吗？这对生产环境使用上有何变化？

另外，比较编译参数，1.9.12.1001还增加了--with-http_slice_module模块。

谢谢！

**Comment by BloodyKnight** [comment]
你好，这个是做了一些修改，pdb的size减小对生产环境没有任何影响的，加上--with-http_slice_module这个编译选项后，就代表编译的nginx版本内置了http_slice模块的能力，详见http://nginx.org/en/docs/http/ngx_http_slice_module.html

**Comment by warmchang** [comment]
ok, thanks!
