### ISSUE TITLE
windows 64位版本的几个疑似bug（稳定性问题）

### ISSUE THREAD

**Issue by foxericlee1** [LomoX-Offical/nginx-openresty-windows#21]
请问能否尽快帮我解决，已经焦头烂额，谢谢。项目用到一半，又无法改变平台。我的qq:8221776
1)Post json时json大小超过一定尺寸后ngx.req.read_body()和local data = ngx.req.get_body_data()就返回nil，超过100k就一定会有这个问题。已经在配置文件设置client_max_body_size 10m;。日志中出现一行warning
2016/03/24 00:14:04 [warn] 5032#5716: *6 a client request body is buffered to a temporary file c:\App\GisService/temp/client_body_temp/0000000007, client: 127.0.0.1, server: , request: "POST /se/v1/test/12345678 HTTP/1.1", host: "127.0.0.1:8080"
2)lua在分析较大json时崩溃（大概100k左右，2000行），报错
nginx: lua atpanic: Lua VM crashed, reason: unknown reason
2016/03/24 08:58:12 [notice] 4756#8144: exiting
3)前期还发现日志输出太多时，开启代码缓存会直接不稳定，也报
nginx: lua atpanic: Lua VM crashed, reason: unknown reason
4)如果http配置段没有默认的defaulttype,在代码中设置content-type也会崩溃

**Comment by foxericlee1** [comment]
如果需要示例的json，我可以提供

**Comment by foxericlee1** [comment]
Win32下的openresty没有这些问题，但我们的C++模块只能用64位的。

**Comment by foxericlee1** [comment]
Win32下的openresty没有这些问题，但我们的C++模块只能用64位的。

**Comment by foxericlee1** [comment]
Win32下的openresty没有这些问题，但我们的C++模块只能用64位的。

**Comment by foxericlee1** [comment]
Win32下的openresty没有这些问题，但我们的C++模块只能用64位的。

**Comment by foxericlee1** [comment]
Win32下的openresty没有这些问题，但我们的C++模块只能用64位的。

**Comment by zqzjz0911** [comment]
麻烦提供一下你们的 请求发送格式。。用 curl 的命令行表示。

**Comment by zqzjz0911** [comment]
更新了新的 cjson.dll 已经解决。
