### ISSUE TITLE
Why it ask for Administarator rights?

### ISSUE THREAD

**Issue by ID453543435** [LomoX-Offical/nginx-openresty-windows#23]
Why it ask for Administarator rights?
How to fix it?

**Comment by zqzjz0911** [comment]
it has some problem when running without admin right.

**Comment by ID453543435** [comment]
what the problems? may be posible fix it

**Comment by ID453543435** [comment]
please say me what the problem, i need version what can run from user woth disabled problem feaure

**Comment by zqzjz0911** [comment]
you can remove manifest info in exe file . but we have not tested it.

**Comment by ID453543435** [comment]
deleting *.mainfest file block starting
