### ISSUE TITLE
"nginx -s quit" can not kill all nginx processes

### ISSUE THREAD

**Issue by coordinate** [LomoX-Offical/nginx-openresty-windows#25]
I test on two computers.

> version: 1.9.14.1001 32bit
> system: windows xp

and

> version: 1.9.14.1001 64bit
> system: windows 7

Uncompress Openresty_For_Windows_1.9.14.1001_32or64Bit.zip and run nginx.exe directly. Then run "nginx -s quit" in the same folder. Just one nginx process is closed and the other one is still running.

**Comment by zqzjz0911** [comment]
you can try param -s stop
