### ISSUE TITLE
支持 IOCP 吗？

### ISSUE THREAD

**Issue by wanjochan** [LomoX-Offical/nginx-openresty-windows#26]
不知道是否支持IOCP呢？

**Comment by zqzjz0911** [comment]
目前不支持，有 select 和 poll 两种模式可以选择。

**Comment by JoKaWare** [comment]
想问一下，现在不支持IOCP的情况下并发是怎么解决的？

**Comment by zqzjz0911** [comment]
多进程 select 模型。

**Comment by zqzjz0911** [comment]
目前 iocp 多进程版本已进入试用阶段，可以在这里：

https://github.com/LomoX-Offical/nginx-openresty-windows

下载试试玩一下。谢谢支持。
