### ISSUE TITLE
Nginx never start

### ISSUE THREAD

**Issue by CriztianiX** [LomoX-Offical/nginx-openresty-windows#27]
Running in windows 10 nginx never start,

C:\nginx> nginx.exe

nginx never is started. No console output and cannot kill it
Try both 32bits and 64bits package.

**Comment by zqzjz0911** [comment]
this need administrator right.

**Comment by CriztianiX** [comment]
i'm administrator, i've ran "run as administrator" and i get the same... 
I also tried: https://github.com/openresty/openresty/blob/master/doc/README-win32.md

**Comment by zqzjz0911** [comment]
what it outputed?

**Comment by CriztianiX** [comment]
The output is a console blocked...
![nginx](https://cloud.githubusercontent.com/assets/1068190/15880178/409346fc-2d01-11e6-9dea-df7059f11d00.png)

**Comment by zqzjz0911** [comment]
it's running.

**Comment by CriztianiX** [comment]
I dont think so, because i run nginx -s stop and the terminal is blocked too

**Comment by zqzjz0911** [comment]
please use task manager to check the nginx process

**Comment by caidongyun** [comment]
juestt   show you error.log

**Comment by liuyangc3** [comment]
有同样的问题，win10 家庭版本

右键以管理员身份运行 nginx.exe, 弹出一个console 瞬间消失

cmd中启动报错
```
$ nginx.exe
nginx: [emerg] bind() to 0.0.0.0:80 failed (10013: An attempt was made to access a socket in a way forbidden by its access permissions)
```
日志error
```
2016/06/16 14:06:35 [emerg] 8136#5644: bind() to 0.0.0.0:80 failed (10013: An attempt was made to access a socket in a way forbidden by its access permissions)
```

**Comment by zqzjz0911** [comment]
哥哥。这权限不足开不了端口啊。

**Comment by zqzjz0911** [comment]
消息框会消失是正常，看任务管理器nginx 进程是否存在。

**Comment by zqzjz0911** [comment]
要右键以管理员身份运行 cmd，然后通过 cmd 启动 nginx 啊，这样才靠谱啊。

**Comment by liuyangc3** [comment]
就是用管理员身份打开的cmd，而且我也确认了，当前用户在adminstrators 组里

win10下 不知道为什么不能开启1024的socket

我把nginx 的http listen端口改成 8080 就可以起动了

**Comment by wen3062** [comment]
win10，一般会默认占用80端口，在“启用和关闭windows功能”处，将他关闭掉就好了。




------------------ 原始邮件 ------------------
发件人: "web";<notifications@github.com>;
发送时间: 2016年6月17日(星期五) 下午2:14
收件人: "LomoX-Offical/nginx-openresty-windows"<nginx-openresty-windows@noreply.github.com>; 

主题: Re: [LomoX-Offical/nginx-openresty-windows] Nginx never start (#27)




就是用管理员身份打开的cmd，而且我也确认了，当前用户在adminstrators 组里
 
win10下 不知道为什么不能开启1024的socket
 
我把nginx 的http listen端口改成 8080 就可以起动了

**Comment by zqzjz0911** [comment]
能不能提供个im联系方式。方便的话我去你哪里远程看看

**Comment by caidongyun** [comment]
做一个 检查 权限启动，还有一个端口检测，防火墙bypass的工具 可行么？ @zqzjz0911

**Comment by caidongyun** [comment]
4: bind() to 0.0.0.0:80 failed (10013: An attempt was made to access a socket in a way forbidden by its access permissions)

端口被占用啊，都是这类问题
