### ISSUE TITLE
请问这个要怎么解决？

### ISSUE THREAD

**Issue by 200p** [LomoX-Offical/nginx-openresty-windows#29]
stack traceback:
coroutine 0:
    [C]: in function 'require'
    E:\Tmp\nginx/lua/hello.lua:2: in function <E:\Tmp\nginx/lua/hello.lua:1>, client: 127.0.0.1, server: v.duba.com, request: "GET / HTTP/1.1", host: "127.0.0.1"
2016/08/04 09:29:03 [error] 30296#28268: *24 lua entry thread aborted: runtime error: error loading module 'zlib' from file '.\zlib.dll':
    找不到指定的程序。

刚找到方法，已经解决了....

local ffi  = require "ffi"
local zlib

if ffi.os == "Windows" then
    zlib = ffi.load "zlib"
else
    zlib = ffi.load "z"
end

**Comment by zqzjz0911** [comment]
请问是什么解决的？

**Comment by caidongyun** [comment]
加载 \zlib.dll' 失败呗，  你看一下 是64位进程还是 32位进程
