### ISSUE TITLE
lua file system不考虑支持下么.我用官方下的dll貌似不能正确加载呢

### ISSUE THREAD

**Issue by onlonely** [LomoX-Offical/nginx-openresty-windows#31]
2016/10/25 12:34:00 [error] 4500#6348: init_worker_by_lua_file error: error loading module 'lfs' from file 'lfs.dll':
    %1 不是有效的 Win32 应用程序。

stack traceback:
    [C]: at 0x005ac900
    [C]: in function 'require'
    lualib/base.lua:9: in main chunk
    [C]: in function 'require'

**Comment by zqzjz0911** [comment]
发给我看看。

**Comment by onlonely** [comment]
http://files.luaforge.net/releases/luafilesystem/luafilesystem/luafilesystem-1.4.2/luafilesystem-1.4.2-win32-lua51.zip

**Comment by zqzjz0911** [comment]
[Uploading lfs.zip…]()

估计是manifest 的问题， 您试试这个？

**Comment by killsen** [comment]
https://luapower.com/lfs/download
