### ISSUE TITLE
How to kill all of the nginx process?

### ISSUE THREAD

**Issue by jeff-wu** [LomoX-Offical/nginx-openresty-windows#33]
I want to kill all the nginx process, but i can not get it. I tried to use `nginx -s stop` and `nginx -s quit` command to do that, but that's all NO effect.

**Comment by zqzjz0911** [comment]
it's work using -s stop
which version of windows are you testing in?

**Comment by caidongyun** [comment]
nginx.exe -s stop

or

Taskkill /IM nginx.exe /F

**Comment by JoKaWare** [comment]
in windows should run as administrator
