### ISSUE TITLE
balancer.set_timeouts()运行出错cannot resolve symbol 'ngx_http_lua_ffi_balancer_set_timeouts

### ISSUE THREAD

**Issue by coverxiaoeye** [LomoX-Offical/nginx-openresty-windows#34]
使用的nginx-openresty-windows版本号:1.11.7.1001 ，修改日志显示：ngx-lua-module 模块更新到 0.10.7了

在lua代码中调用balancer.set_timeouts(6,nil,nil)，报错，异常信息如下：
[error] 1928#10932: *1 failed to run balancer_by_lua*: .\ngx\balancer.lua:139: cannot resolve symbol 'ngx_http_lua_ffi_balancer_set_timeouts': 找不到指定的程序。

同样的代码，使用openresty官网的二进制版本openresty-1.11.2.2-win32.zip ，测试正常，麻烦看下 是不是  模块ngx-lua-module未成功更新？

查看openresty官网，在ngx_lua  0.10.6版本已经增加该接口了
feature: added pure C API for setting upstream request connect/send/read timeouts in balancer_by_lua* on a per session basis. thanks Jianhao Dai for the original patch.

**Comment by BloodyKnight** [comment]
@coverxiaoeye  您好，这个问题出现的原因已经找到，原因是函数没有导出（见ngx/balancer.lua中的ffi导出的c函数），如果有条件编译的话可以在源码中的src/nginx/nginx.def文件中加入这些导出函数，重新编译就可以解决问题，今天晚上准备重新编译一个新版本，修复这些问题，明早发布。
谢谢您的反馈！

**Comment by coverxiaoeye** [comment]
@BloodyKnight 昨天使用版本1.11.7.1002进行了验证，问题已修复。超赞，非常感谢！
