### ISSUE TITLE
Download Link down can you check address ?

### ISSUE THREAD

**Issue by Lethea** [LomoX-Offical/nginx-openresty-windows#35]

**Comment by zqzjz0911** [comment]
please check the release page to get download url.thx.

**Comment by siaro30** [comment]
Download url not working for Europe.
Can you publish a other locations ?

**Comment by zqzjz0911** [comment]
you can link in to the [release page](https://github.com/LomoX-Offical/nginx-openresty-windows/releases)  to get the download link...
