### ISSUE TITLE
iocp版怎么配置呢？

### ISSUE THREAD

**Issue by wanstonq** [LomoX-Offical/nginx-openresty-windows#36]
events {
	use  iocp;
       worker_connections 1024;
}

采用这样的配置后，页面会一直在等待加载

**Comment by zqzjz0911** [comment]
请使用 如下版本：
IOCP版本(开发版本)

版本号:1.11.5.1001

32 位下载地址: http://pan.baidu.com/s/1kVdhEPh

64 位下载地址: http://pan.baidu.com/s/1o7IcPVO

**Comment by wanstonq** [comment]
transmitfile的功能好像加入

**Comment by zqzjz0911** [comment]
暂时没有这个功能

**Comment by ZJArcher** [comment]
IOCP版本最后提交是1年前，难道被放弃了？

**Comment by zqzjz0911** [comment]
等待试用反馈啊

**Comment by jxskiss** [comment]
反馈一下使用情况，开发环境，使用到 lor/orange/mysql/pgmoon 一些包，正常没遇到什么问题，不过 openresty 最新更新的一些东西用不上，比如 `local ngx_re = require "ngx.re"`.

很棒，感谢！

**Comment by zqzjz0911** [comment]
感谢🙏
