### ISSUE TITLE
请问能把淘宝的contact模块打包进去么？

### ISSUE THREAD

**Issue by wind930** [LomoX-Offical/nginx-openresty-windows#4]
请问能把淘宝的 tengine contact (https://github.com/alibaba/nginx-http-concat) 模块打包进去么？

**Comment by caidongyun** [comment]
柱子要不要做一个管理平台，填写模块 就直接弄进去

**Comment by caidongyun** [comment]
这个你改一下module 代码 就行了把

**Comment by zqzjz0911** [comment]
需要编译哦。

**Comment by wind930** [comment]
呵呵，最近没时间搞，有时间我也来尝试编译看看
总感觉你那个目录有点乱啊

**Comment by zqzjz0911** [comment]
openresty 原版就是这样了，按模块分好，挺好的。

**Comment by BloodyKnight** [comment]
concat模块已经编译进去，请到 github.com/LomoX-Offical/nginx-openresty-windows 获取最新版本的下载链接
