### ISSUE TITLE
我在添加stream-lua-nginx-module模块的时候遇到这样的报错，请问你有遇到过吗？在nmake阶段的时候

### ISSUE THREAD

**Issue by yaojixiang1975** [LomoX-Offical/nginx-openresty-windows#40]
../stream_lua/src/ngx_stream_lua_sleep.c(89): error C2039: “uri”: 不是“ngx_
ream_lua_request_s”的成员
e:\nginx\nginx-openresty-windows-master\src\stream_lua\src\ngx_stream_lua_requ
t.h(20): note: 参见“ngx_stream_lua_request_s”的声明
NMAKE : fatal error U1077: “"d:\Program Files (x86)\Microsoft Visual Studio\2
7\Community\VC\Tools\MSVC\14.10.25017\bin\HostX86\x86\cl.EXE"”: 返回代码“0x2

**Comment by zqzjz0911** [comment]
还没试过。

**Comment by yaojixiang1975** [comment]
我把出错的代码注释掉就可以了。估计是春哥的问题。出错的代码就是一段日志而已，不影响功能

**Comment by zqzjz0911** [comment]
要注意nginx 的版本和 module 的版本的匹配。
