### ISSUE TITLE
这个版本编译有64位windows版本么？

### ISSUE THREAD

**Issue by yosaku01** [LomoX-Offical/nginx-openresty-windows#5]
百度网盘提供的是32位版本的

**Comment by zqzjz0911** [comment]
马上会提供的。去我们QQ群逛逛，以便获得最新信息：167813458

**Comment by caidongyun** [comment]
https://github.com/caidongyun/winsvr-bin

**Comment by caidongyun** [comment]
https://github.com/LomoX-Offical/winsvr-bin

**Comment by BloodyKnight** [comment]
64位版本已经发布，请到 github.com/LomoX-Offical/nginx-openresty-windows 获取最新版本的下载链接
