### ISSUE TITLE
一些在luajit.exe下正常运作的c的库经常不能运作

### ISSUE THREAD

**Issue by newsoulisme** [LomoX-Offical/nginx-openresty-windows#6]
这个win版本的openresty非常好用和强大，开发效率和运行效率都不错.  有个问题是经测试，一些第3方的c库在用luajit.exe下直接调用，表现是正常的. 但在openresty下就不对劲了，表现是浏览器访问对应脚本，会不响应直至超时，也没报错。目前观察到的有lfs(luaFileSytem) , lpeg , luacom等。

**Comment by newsoulisme** [comment]
用近期的版本可以兼容了，感谢！

**Comment by caidongyun** [comment]
fixed
