### ISSUE TITLE
配置不兼容

### ISSUE THREAD

**Issue by mlr3000** [LomoX-Offical/nginx-openresty-windows#7]
nginx: [emerg] invalid lua shared dict size "10m" in e:\nginx/conf/nginx.conf

 lua_shared_dict dogs 10m;

最新64 bit 版本

**Comment by caidongyun** [comment]
配置原文件  放出来看看

**Comment by zqzjz0911** [comment]
明天我回去之后看看，我有点思路了。

**Comment by BloodyKnight** [comment]
@mlr3000 您好，谢谢您的反馈，我们已经紧急修复了这个问题。
新的二进制文件可以从下面的URL获取：http://pan.baidu.com/s/1dDAVQq1
再次表示感谢！
